# Generated by Django 4.0 on 2021-12-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('views', models.PositiveIntegerField(blank=True, null=True, verbose_name='Просмотры')),
                ('clicks', models.PositiveIntegerField(blank=True, null=True, verbose_name='Клики')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена')),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Средняя стоимость клика')),
                ('cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Средняя стоимость 1000 показов')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ('date',),
            },
        ),
    ]
